### ISSUE TITLE
Arch Package

### ISSUE THREAD

**Issue by ulrichSchreiner** [wader/fq#19]
hi,

great tool. just want you to know that i created an ARCH package, so users of arch linux can now simply install it by
~~~
$ yay -S fq-bin
~~~

**Comment by wader** [comment]
Thanks! how does it work, builds from source on install or will be updates per version?

**Comment by ulrichSchreiner** [comment]
it installs the released binary from this github project and uses the same version. so for every release i have to update the package here: https://aur.archlinux.org/packages/fq-bin

**Comment by wader** [comment]
Ok, good to know. No sure how often i will do releases yet

**Comment by ulrichSchreiner** [comment]
no problem. i starred the repo, so i get an email if there is a new release. if  one has  an account for "aur.archlinux.org" you can also simply flag a package as outdated and i will be notified (there is a link in the project page for this).

**Comment by wader** [comment]
👍 Let me know if there is something i can do to make packaging easier. Should it end up in the install instructions eventually? Is there some review process to make it ”official” etc?

**Comment by ulrichSchreiner** [comment]
at the momemt it is really easy. i only have to do a `make latestrelease` and my system fetches your latest release. then i have to push the changes to AUR. in the long run, you could do this by yourself if you have an AUR account. everything is in the repository (https://aur.archlinux.org/fq-bin.git).

and "no" there is no review process to make this official. everyone can put an package in the AUR-repo and then every arch-user can install it with `yay` or a similar packaging tool.

the best thing you can do is to do regular releases when you have important bug fixes or some new features.

**Comment by wader** [comment]
Nice! On the road atm but will add this to the readme somehow. Also like that there is some jq in the makefile :)

**Comment by dundee** [comment]
Hi,
I have added package built from sources in the AUR as well: https://aur.archlinux.org/packages/fq/

@ulrichSchreiner Do you want to be added as co-maintainer?

Ad review process: We will have to wait for some TU (Arch Trusted User) to notice `fq` and then will migrate it into `community` repository. It can take several months or years, depends on how many users will use it :)

**Comment by wader** [comment]
@dundee 👍 

I guess shorter is preferred?

**Comment by dundee** [comment]
They both have their benefit and place in the AUR. `fq-bin` is better for users that don't want to compile the sources and don't adhere to security too much. `fq` is better for the rest and for migration to `community` repository afterwards.

**Comment by wader** [comment]
Ok, i don't know much about arch so will have to relay on you ppl what is best. Sounds like both can exist? let me know or send PR what is reasonable to add to install instructions.

**Comment by dundee** [comment]
Yes, it's correct that both will exist. Users can decide which one fits their needs best. I will send a PR.

**Comment by wader** [comment]
Thanks @dundee @ulrichSchreiner and let me know if there is something i can do make it easier to package fq
