### ISSUE TITLE
Make packages importable

### ISSUE THREAD

**Issue by 89z** [wader/fq#282]
Currently it seems none of the packages are importable

https://godocs.io/github.com/wader/fq/format/mp4
https://godocs.io/github.com/wader/fq/format/mp3

because all items are marked as private. Can you export some items so that the packages can be used?

**Comment by wader** [comment]
Hello, currently none of the fq packages have stable APIs as things will probably change, and the decoder implementations are currently not ment to be used directly. You can import format packages but that will only register them to a default registry, a bit similar to how `image/*` in std work.

That said it is possible to instantiate your own fq interpreter. Import/register your own formats or standard fq formats (or use the all package), implement a small version of https://pkg.go.dev/github.com/wader/fq@v0.0.7/pkg/interp#OS and use https://pkg.go.dev/github.com/wader/fq@v0.0.7/pkg/interp#New and then use `Eval` to run `open | decode | tovalue` etc to get values.
There is probably some more details i missed, i can give a more complete example if you want.

Could you tell me a bit more what your use case is?

**Comment by 89z** [comment]
I have no idea if FQ is suited for my use case, but ultimately I am trying to decrypt some MP4 files. I have the keys as needed, I just need software to do the decryption. I have used tools like FFmpeg and Mp4Decrypt with success, but I would like a Go implementation if possible, so that I can integrate it with other software.

I am currently using `edgeware/mp4ff` for this purpose, but it seems to crash on certain input, so I am trying to find an alternate solution.

**Comment by wader** [comment]
I see, then i think your probably better of with edgeware/mp4ff or something similar. But it might help to use fq to inspect crashing files to get some hints of what is going on. I would guess there is bug or something fishy with the sample chunk/mapping tables etc.

Have any sample files and does fq decode them properly?

**Comment by 89z** [comment]
Using this file (444 KB):

~~~
https://user-images.githubusercontent.com/73562167/170490911-a4bb62b6-b841-4e1c-9158-ba7389e1a168.mp4
~~~

I get this result:

~~~
> fq . 170490911-a4bb62b6-b841-4e1c-9158-ba7389e1a168.mp4
error: 170490911-a4bb62b6-b841-4e1c-9158-ba7389e1a168.mp4: probe: failed to
decode (try -d FORMAT)
~~~

**Comment by wader** [comment]
Hmm there is a type here https://github.com/wader/fq/blob/master/format/mp4/boxes.go#L1055 should be 16*8 after that it can decode at least. But don't see any obvious things. Will fix bug and look more closer tomorrow.

btw you can do `fq -d mp4 . file` etc to force a format, will give some more context what goes wrong.

**Comment by wader** [comment]
#283 should fixes the fq issues, hope it is ok to use the pssh boxes from the file for regression tests?

**Comment by wader** [comment]
tried ffmp4, looks like it fails during reading of traf box children and i don't see trun box in the backtrace, only unknown box.. so maybe does not read some box correctly ending up reading some non-box header bytes as a header?
```
$ go run examples/decrypt-cenc/main.go -i ~/Downloads/170490911-a4bb62b6-b841-4e1c-9158-ba7389e1a168.mp4 -o bla.mp4 -k "00000000000000000000000000000001"
panic: runtime error: slice bounds out of range [5397:5391]

goroutine 1 [running]:
github.com/edgeware/mp4ff/bits.(*FixedSliceReader).ReadBytes(0x10acda4?, 0xd10000c000126480?)
	/Users/wader/src/mp4ff/bits/fixedslicereader.go:205 +0xcb
github.com/edgeware/mp4ff/mp4.DecodeUnknownSR({{0xc000128190?, 0xc00010c240?}, 0xc000128190?, 0x4?}, 0x115f?, {0x1136a88, 0xc000126480})
	/Users/wader/src/mp4ff/mp4/unknown.go:29 +0x4b
github.com/edgeware/mp4ff/mp4.DecodeBoxSR(0x17135c0?, {0x1136a88, 0xc000126480})
	/Users/wader/src/mp4ff/mp4/boxsr.go:145 +0xe5
github.com/edgeware/mp4ff/mp4.DecodeContainerChildrenSR({{0xc00012812c?, 0x0?}, 0x101081d?, 0x4?}, 0x7d2, 0x280f, {0x1136a88, 0xc000126480})
	/Users/wader/src/mp4ff/mp4/container.go:62 +0x135
github.com/edgeware/mp4ff/mp4.DecodeTrafSR({{0xc00012812c?, 0xc00010c240?}, 0xc00012812c?, 0x4?}, 0xc00014b9e8?, {0x1136a88?, 0xc000126480?})
	/Users/wader/src/mp4ff/mp4/traf.go:46 +0x49
github.com/edgeware/mp4ff/mp4.DecodeBoxSR(0x203000?, {0x1136a88, 0xc000126480})
	/Users/wader/src/mp4ff/mp4/boxsr.go:147 +0xb5
github.com/edgeware/mp4ff/mp4.DecodeContainerChildrenSR({{0xc000128118?, 0xc000122028?}, 0xc000152000?, 0x2055?}, 0x7ba, 0x280f, {0x1136a88, 0xc000126480})
	/Users/wader/src/mp4ff/mp4/container.go:62 +0x135
github.com/edgeware/mp4ff/mp4.DecodeMoof({{0xc000128118?, 0xc00010c210?}, 0xc000128118?, 0x4?}, 0x7b2, {0x11346f8, 0xc000122028})
	/Users/wader/src/mp4ff/mp4/moof.go:31 +0x134
github.com/edgeware/mp4ff/mp4.DecodeBox(0xc00012c070?, {0x11346f8, 0xc000122028})
	/Users/wader/src/mp4ff/mp4/box.go:280 +0xb5
github.com/edgeware/mp4ff/mp4.DecodeFile({0x11346f8?, 0xc000122028}, {0x0, 0x0, 0x10ef560?})
	/Users/wader/src/mp4ff/mp4/file.go:156 +0x237
main.decryptMP4withCenc({0x11346f8?, 0xc000122028?}, {0xc00014bea8, 0x10, 0x20}, {0x1134718, 0xc000122030})
	/Users/wader/src/mp4ff/examples/decrypt-cenc/main.go:76 +0x6d
main.start({0x11346f8, 0xc000122028}, {0x1134718, 0xc000122030}, {0x7ff7bfeffa84?, 0x110fa97?})
	/Users/wader/src/mp4ff/examples/decrypt-cenc/main.go:52 +0xd2
main.main()
	/Users/wader/src/mp4ff/examples/decrypt-cenc/main.go:36 +0x212
exit status 2
```

**Comment by wader** [comment]
Do you have the encryption key? :)

**Comment by 89z** [comment]
> hope it is ok to use the pssh boxes from the file for regression tests?

I wouldn't recommend it. I don't own the copyright to the linked video. Although I think its less than 10 seconds, so probably fair use?

> Do you have the encryption key? :)

~~~
680a46ebd6cf2b9a6a0b05a24dcf944a
~~~

**Comment by wader** [comment]
> > hope it is ok to use the pssh boxes from the file for regression tests?
> 
> I wouldn't recommend it. I don't own the copyright to the linked video. Although I think its less than 10 seconds, so probably fair use?

Sorry should have been clear it is only the pssh boxes and the first ftyp box ~1236 bytes total.

> > Do you have the encryption key? :)
> 
> ```
> 680a46ebd6cf2b9a6a0b05a24dcf944a
> ```

👍

**Comment by wader** [comment]
Had a deeper look at the mp4ff problem. I think the issue is that the file uses http://fileformats.archiveteam.org/wiki/Protected_Interoperable_File_Format which is not support yet. It ends up here https://github.com/edgeware/mp4ff/blob/master/mp4/uuid.go#L72 and does not read enough bytes. I did quick and dirt hack to read the bytes and return the correct box size and then it decodes fine but there has to no some more work to make it actually decrypt. Maybe should file an issue at mp4ff?

**Comment by 89z** [comment]
> I think the issue is that the file uses http://fileformats.archiveteam.org/wiki/Protected_Interoperable_File_Format which is not support yet.

Lovely :(

> It ends up here https://github.com/edgeware/mp4ff/blob/master/mp4/uuid.go#L72 and does not read enough bytes.

FYI its usually better to do a permalink, for that type of link. Otherwise the link will be invalid as soon as someone changes the file. On the link you gave, you can click the three dots on the left, and click "Copy permalink", which gives this instead:

https://github.com/edgeware/mp4ff/blob/e51225e48fbb04a79713ef569347075ebacffe3b/mp4/uuid.go#L72

> I did quick and dirty hack to read the bytes and return the correct box size and then it decodes fine but there has to be some more work to make it actually decrypt.

I think I just need `mp4.DecodeFile` to stop crashing. If that can be fixed, I already have code for decrypting. So if you have some patch, I would be very interested in it!

**Comment by wader** [comment]
> FYI its usually better to do a permalink, for that type of link. Otherwise the link will be invalid as soon as someone changes the file. On the link you gave, you can click the three dots on the left, and click "Copy permalink", which gives this instead:
> 
> https://github.com/edgeware/mp4ff/blob/e51225e48fbb04a79713ef569347075ebacffe3b/mp4/uuid.go#L72

Good point, thanks

> > I did quick and dirty hack to read the bytes and return the correct box size and then it decodes fine but there has to be some more work to make it actually decrypt.
> 
> I think I just need `mp4.DecodeFile` to stop crashing. If that can be fixed, I already have code for decrypting. So if you have some patch, I would be very interested in it!

Sure, pushed a branch here https://github.com/wader/mp4ff/tree/piff-hack

**Comment by 89z** [comment]
Thanks. Your code does fix panics and errors, but my decryption code doesn't work on the result. So I guess the decryption for PIFF is different too? I am able to decrypt the file I linked with Mp4Decrypt or FFmpeg. I am also able to decrypt non PIFF files with my own code. But I cant seem to decrypt PIFF files with my code.

**Comment by wader** [comment]
Guess so, probably have to find some ISOBMFF/PIFF specification or sneak peak at GPAC or some other implementation what has to be done.

**Comment by wader** [comment]
Ok to close issue? feel free to comment with piff spec etc if you find something, maybe i will look into adding some kind of cenc support to fq at some point.

**Comment by 89z** [comment]
Yeah I guess we are done here. Thanks for the great help. Crappy result, but not your fault. Maybe I can find a Python decryptor for PIFF, and translate that. I would like to avoid Bento4 if possible, as reading C++ makes my head hurt.

**Comment by wader** [comment]
Wish you good luck! and at least we improved fq :)

**Comment by 89z** [comment]
Hey, I wanted you to know, I think I figured it out. Using `mp4dump`, I got this:

~~~
[moof] size=8+6657
  [traf] size=8+6633
    [senc] size=12+2308, flags=2
      sample info count = 144
    [A2394F525A9B-4F14-A244-6C42-7C648DF4] size=28+2308, flags=2
      sample info count = 144
~~~

so both CENC and PIFF are there. I remember from my own code, that I needed to remove the encryption boxes after decrypting, otherwise the output file wouldn't play. So it might just be that I need to remove the PIFF box in addition to the CENC box. I think the code is here:

https://github.com/edgeware/mp4ff/blob/e51225e48fbb04a79713ef569347075ebacffe3b/mp4/traf.go#L266-L268

Its late, so I might try it tomorrow.

**Comment by 89z** [comment]
It worked! Just adding another case fixed it:

~~~go
case "uuid":
   nrBytesRemoved += ch.Size()
~~~

**Comment by wader** [comment]
Nice! do you already know the key and sample encryption mode in advance somehow?

Got a bit curious to learn more about this now, will probably try add some more senc and uuid box decoding to fq. If i remember correctly one have to know the IV size to decode senc properly? that that was why i skipped at the time

**Comment by 89z** [comment]
> Nice! do you already know the key and sample encryption mode in advance somehow?

I dont really know too much about this stuff. I just wanted to use a Go package instead of having to call a command line tool. So I am kind of just figuring this out as I go. I do know that the key needs to be provided by the user:

https://github.com/edgeware/mp4ff/blob/82be3164fbc5cc6f4b3ce5880e2ebb3dee771b62/mp4/crypto.go#L30-L31

> If i remember correctly one have to know the IV size to decode senc properly? that that was why i skipped at the time

I have tested files from three sites, they all used the "short IV". So until I find a site thats different, I am just assuming they all do that. I think this is the code you want to look at for that:

https://github.com/edgeware/mp4ff/blob/e51225e48fbb04a79713ef569347075ebacffe3b/examples/decrypt-cenc/main.go#L222-L229
