### ISSUE TITLE
[question] Is there a way to output raw bytes for selected field?

### ISSUE THREAD

**Issue by Rogach** [wader/fq#33]
For example I can view the text of a tag in MP3 file using

```
fq '.headers[0].frames[0].text' file.mp3
```

But is there a way to dump the raw bytes from this text to stdout for further processing? For example somethind like this:

```
fq --some-option '.headers[0].frames[0].text' file.mp3 | iconv
```

I looked through the documentation, but didn't see anything like it.

P.S. Thank you for this tool, it is very nice - simple, but extremely useful.

**Comment by wader** [comment]
Hi, thanks! Yes you can use `tobytes` or `tobits` to get the raw bits representing a value.
```sh
$ fq  '.headers[0].frames[0].text | tobytes' testfiles/test.mp3 | hexdump -C
00000000  62 6c 61 00                                       |bla.|
00000004
```
Note that fq will only output raw bytes if stdout it not a tty.

**Comment by Rogach** [comment]
Shame on me, this indeed was in the documentation but I missed it. Thanks!

**Comment by wader** [comment]
No problem, i should really improve the documentation soon. Note that those functions might return data that include length prefix or null terminator bytes etc.
