### ISSUE TITLE
mkvmerge's output with FLAC cannot be read

### ISSUE THREAD

**Issue by ktmf01** [wader/fq#403]
First of all, I'm not sure this is a problem with fq at all, but it seems most likely.

For the flac specification, I was studying encapsulation for FLAC in matroska (fq is a great help here, thanks!) and while fq does wonderfully for ffmpeg, I wanted to check with mkvmerge. However, fq is unable to read these files. From the fq output (when forced to matroska) it seems mkvmerge adds a byte in front of the sync code, but I'm not sure.

Here is a FLAC file muxed to mkv with ffmpeg and mkvmerge. The first works fine, the second does not.

[File muxed with ffmpeg](http://www.audiograaf.nl/misc_stuff/sweep-with-DC.mka)
[File muxed with mkvmerge](http://www.audiograaf.nl/misc_stuff/sweep-with-DC.mkvmerge.mka)

I've skimmed over the mkvmerge sources but couldn't find anything obvious. Furthermore, the mkvmerge file plays fine on ffmpeg, and produces no warnings or notices related to this extra byte even on the highest verbosity level. Therefore I think this is either a problem with fq or something that is left unspecified in the matroska embedding spec. The latter would obviously be very interesting for me :)

I hope you can help me out here. Thanks in advance!

**Comment by wader** [comment]
Interesting! sorry a bit busy this weekend, parents are visiting, but I
have some guesses!

On Fri, Aug 26, 2022 at 9:35 PM Martijn van Beurden <
***@***.***> wrote:

> First of all, I'm not sure this is a problem with fq at all, but it seems
> most likely.
>
> For the flac specification, I was studying encapsulation for FLAC in
> matroska (fq is a great help here, thanks!) and while fq does wonderfully
> for ffmpeg, I wanted to check with mkvmerge. However, fq is unable to read
> these files. From the fq output (when forced to matroska) it seems mkvmerge
> adds a byte in front of the sync code, but I'm not sure.
>
> Here is a FLAC file muxed to mkv with ffmpeg and mkvmerge. The first works
> fine, the second does not.
>
> File muxed with ffmpeg
> <http://www.audiograaf.nl/misc_stuff/sweep-with-DC.mka>
> File muxed with mkvmerge
> <http://www.audiograaf.nl/misc_stuff/sweep-with-DC.mkvmerge.mka>
>
> I've skimmed over the mkvmerge sources but couldn't find anything obvious.
> Furthermore, the mkvmerge file plays fine on ffmpeg, and produces no
> warnings or notices related to this extra byte even on the highest
> verbosity level. Therefore I think this is either a problem with fq or
> something that is left unspecified in the matroska embedding spec. The
> latter would obviously be very interesting for me :)
>
> I hope you can help me out here. Thanks in advance!
>
Sounds like a problem with fq :) The only thing I can come up with right
away is this "lacing" thing that some (only xiph? similar to ogg packet
muxing) codecs use in matroska. And a diff between two simples blocks from
the files seems to indicate that might be the case:

$ fq -n -d matroska 'def f: input | first(grep_by(.id=="simple_block"));
diff(f; f)' sweep-with-DC.mka sweep-with-DC.mkvmerge.mka
{
  "flags": {
    "lacing": {
      "a": 0,
      "b": 2
    }
  },
  // ... cut away some diff ...
}

I don't know what lacing 2 means but i think that could be a good start to
digg. The vorbis code in matroska does some lacing already but there is
some TODO, so maybe i skipped something? maybe it's possible to do some
kind of shared lacing decode thingy there, but first i would probably just
some ugly hack to see if that is the case.

Let me know how it goes and i'm happy to help more after the weekend

-Mattias

**Comment by ktmf01** [comment]
Thanks for the clue. No worries about timing, the spec isn't going anywhere.

Anyway, Xiph lacing is not specific to Xiph codecs. It is simply something inspired by ogg, so it can be used for any codec. Lacing is however only used for small frames.

According to the spec, lacing bits are 0b00 with no lacing, are 0b01 with Ogg-inspired lacing (referred to as Xiph lacing, for very small frames only), 0b10 for EBML lacing (for larger frames) and 0b11 for fixed-size lacing (for blocks of exactly the same size only.

I'll take a look now that I know where to look.

**Comment by ktmf01** [comment]
When I run mkvmerge with `--disable-lacing` everything works fine, so lacing indeed seems the problem.

Sadly, I'm not used to Go's syntax so I can't make head nor tail of the code surround the laces. I wanted to contribute here, but I don't even know where to start.

Please don't feel hurried. I'll close this issue as lacing it is already on the TODO list and there's no need to get this fixed any sooner as I know now this is not something in the FLAC embedding spec I need to worry about, and I can study mkvmerge's output with `--disable-lacing` as well.

**Comment by wader** [comment]
👍 Nice thanks for confirming, and no worries I will probably have a look adding proper lacing support next week or so. And please don't hesitate ask about the code or golang, happy to help out if you wish to contribute code fixes.
