### ISSUE TITLE
Seeking from end of stream

### ISSUE THREAD

**Issue by dgmcdona** [wader/fq#416]
I see that it is possible to seek relative to the current position or the beginning of the file. Is it possible to seek from the end, or does that functionality  need to be added? Apple's binary plist format has a 32-byte trailer at the end of the file that contains metadata required for decoding the rest of the objects.

**Comment by wader** [comment]
Hi, nope don't think there is. What would be a good API for it? seek absolute with negative position? as a workaround you can do `d.SeekAbs(d.Len() - 32*8)` for now.

Binary plist support would be great! plan on sending a PR eventually? BTW i did a xml plist to json hack some time ago https://github.com/wader/fq/wiki/snippets (see fromplist), could maybe be included in standard fq also.

**Comment by dgmcdona** [comment]
Ah yes, that will work just fine for now. Not sure what the best API for it would be. My first thought would be to implement something like the `io.Seeker` interface.

Working on binary plists right now, hopefully will submit a PR by next weekend. `plutil` is not great and I'd love to see `fq` fill a serious need there. There are other tools out there, but `fq` is super cool and should totally support this.

**Comment by wader** [comment]
> Ah yes, that will work just fine for now. Not sure what the best API for it would be. My first thought would be to implement something like the `io.Seeker` interface.

Ah yeah actually decode uses bitio.Seeker which is modelled after io.Seeker. Maybe i had some idea to keep the decode API more high level or not expose bitio things into decoders. Let us think a bit about it, no hurry i guess?

> Working on binary plists right now, hopefully will submit a PR by next weekend. `plutil` is not great and I'd love to see `fq` fill a serious need there. There are other tools out there, but `fq` is super cool and should totally support this.

👍  and thanks :) Do you plan on some kind of encode support also? currently at least for binary formats fq is mostly about decoding. XML, YAML etc has decode/encode support by using a common jq value representation. I've thought about doing something similar for binary encode but no plan at the moment, it can get quite complicated.

**Comment by wader** [comment]
Ok to close? and progress on binary plist?

**Comment by dgmcdona** [comment]
You can close it. I’ve made some good progress with the plist format, just sorting out some bugs. I don’t plan on doing encode support right now, maybe down the road?

**Comment by wader** [comment]
Nice, yeap lets start with decode, also encoding in fq is a bit up in the air
