### ISSUE TITLE
[Question] what do 'f' and 'q' mean?

### ISSUE THREAD

**Issue by ccmywish** [wader/fq#569]
The issue is just a simple question: What do `f` and `q` mean?

I only know `jq` is a `JSON processor`, so what does `q` mean? 

And what does `f` in `fq` mean? File?

It's a cryptic name, so I want to record it in [cryptic_computer dictionary](https://github.com/cryptic-resolver/cryptic_computer)

**Comment by wader** [comment]
Hey, i think jq comes from json query, fq is file/format query, not sure myself :) i can help digg deeper into the jq name if you like

**Comment by ccmywish** [comment]
I agree with you that `q` means `query`.  Many times, I've found that abbreviations that at first seemed baffling to me lead to simple words. 

Thanks for your help!

**Comment by wader** [comment]
I think the closest i can find in the jq repo is https://github.com/stedolan/jq/blob/cff5336ec71b6fee396a95bb0e4bea365e0cd1e8/libjq.pc.in#L8

Both the first version in haskell (https://github.com/stedolan/jq/commit/eca89acee00faf6e9ef55d84780e6eeddf225e5c) and C (https://github.com/stedolan/jq/commit/2002dc1a2f4c35478b55149bc1a731e65d9a4268) are named "jq" but no reference to "query" what i can see

**Comment by ccmywish** [comment]
Thanks for your kind help! 

I've added `jq` and `fq` to the dictionary: https://github.com/cryptic-resolver/cryptic_computer/commit/f67f14b2cbdedf6f6f66870932763f90a1a20d00
