### ISSUE TITLE
Feature request: Torrent metainfo Support

### ISSUE THREAD

**Issue by waweic** [wader/fq#63]
I think it would be really great to be able to look into .torrent files. Is this in the scope of this project?

**Comment by wader** [comment]
Good idea, have a look at #64, with that you can do this:
```
$ fq -d bencode d bbb.torrent
... detailed tree dump

$ fq -d bencode tovalue bbb.torrent
... detailed structure as JSON 

$ fq -rd bencode 'bencode_torepr | .["announce-list"][][] | tovalue' bbb.torrent
udp://tracker.openbittorrent.com:80/announce
udp://tracker.publicbt.com:80/announce

```

`bencode_torepr` is used to convert the detailed structure into something similar to JSON. I hope in the future come up with some nicer way to do this conversion, maybe a `torepr` function etc.

**Comment by wader** [comment]
Also currently the bencode decoder is not part of the probe group so have to use `-d`. Not sure the binary format is distinguishable enough for probing or not.
