### ISSUE TITLE
mp3 file with id3 2.4.0 got killed from console output

### ISSUE THREAD

**Issue by morrispetris** [wader/fq#690]
### What version are you using (`fq -v`)?
<pre>
$ fq -v
$ 0.6.0 (linux amd64)
</pre>

### How was fq installed?
manually built from source
<pre>
go build -o fq .
</pre>

### Can you reproduce the problem using the latest release or master branch?
yes

### What did you do?
7.mp3 is a file with id3: 2.4.0. No problem with 2.3.0
<pre>
peter@ubuntu:~/tmp/fq$ ./fq .headers[0].frames[5] ~/tmp/7.mp3
Killed
peter@ubuntu:~/tmp/fq$ ./fq -d mp3 dv ~/tmp/7.mp3
Killed
peter@ubuntu:~/tmp/fq$
</pre>

### What result did you expect?
hex view from mp3 file

### What did you see instead?
just got "Killed" from the console output

**Comment by wader** [comment]
Hi, thanks for the report! That is weird, guessing something tries to allocate a lot of memory. Is it possible to share the file or at least the header? if you don't wan't it in public you can send it in an email also. Otherwise i will have to debug-guide you somehow.

**Comment by morrispetris** [comment]
Thanks. I've sent you email, with the file.

**Comment by wader** [comment]
Thanks! it seem decode fine with master version which is not that different from 0.6. So i wonder if you might be running this on a system with not much memory? fq do use a lot of memory at the moment.

```sh
➜  fq git:(master) ✗ go run . -o line_bytes=10 -d mp3 . ~/Downloads/7.mp3
         │00 01 02 03 04 05 06 07 08 09│0123456789│.{}: /Users/wader/Downloads/7.mp3 (mp3)
0x0000000│49 44 33 04 00 00 00 03 3d 75│ID3.....=u│  headers[0:1]:
0x000000a│54 53 53 45 00 00 00 0e 00 00│TSSE......│
*        │until 0xdefe.7 (57087)       │          │
0x000def8│                     ff fb 54│       ..T│  frames[0:102265]:
0x000df02│00 00 00 00 00 00 00 00 00 00│..........│
0x000df0c│00 00 00 00 00 00 00 00 00 00│..........│
*        │until 0x12c79be.7 (19634880) │          │
0x12c79b8│                     54 41 47│       TAG│  footers[0:1]:
0x12c79c2│00 00 00 00 00 00 00 00 00 00│..........│
0x12c79cc│00 00 00 00 00 00 00 00 00 00│..........│
*        │until 0x12c7a3e.7 (end) (128)│          │
```

BTW if you you'r only interested in the id3v2 tag you can use `-d id3v2` which will use a lot less memory as fq will not decode any frames (notice the `gap0` field which contains the frames)
```sh
➜  fq git:(master) ✗ go run . -o line_bytes=10 -d id3v2 . ~/Downloads/7.mp3
         │00 01 02 03 04 05 06 07 08 09│0123456789│.{}: /Users/wader/Downloads/7.mp3 (id3v2)
0x0000000│49 44 33 04 00 00 00 03 3d 75│ID3.....=u│  header{}:
0x000000a│54 53 53 45 00 00 00 0e 00 00│TSSE......│  frames[0:9]:
0x0000014│03 4c 61 76 66 35 38 2e 32 30│.Lavf58.20│
*        │until 0xcb.7 (194)           │          │
0x00000c8│            00 00 00 00 00 00│    ......│  padding: raw bits (all zero)
0x00000d2│00 00 00 00 00 00 00 00 00 00│..........│
*        │until 0xdefe.7 (56883)       │          │
0x000def8│                     ff fb 54│       ..T│  gap0: raw bits
0x000df02│00 00 00 00 00 00 00 00 00 00│..........│
0x000df0c│00 00 00 00 00 00 00 00 00 00│..........│
*        │until 0x12c7a3e.7 (end) (1963│          │
```

**Comment by morrispetris** [comment]
Thanks. Let me try in another machine

**Comment by morrispetris** [comment]
Thanks. It works when I used another machine with 4GB RAM.

**Comment by wader** [comment]
👍  good, there is 100000+ frames to keep track of so will use some memory :) but thanks for the report and i will try figure if there is some better way to fail on OOM that explains what is going on.
