### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by wangsongyan** [wader/fq#692]
**jq**  for binary formats - tool, language and decoders for working with binary and text formats
![20230606183933](https://github.com/wader/fq/assets/5162138/8dc6a15a-f42f-4ea5-8bcb-3690b00f0747)

**Comment by wader** [comment]
Hi, you mean it should say "fq for binary formats"? my thinking was that the repo name is fq so maybe enough and i want to mention jq. On possibility is to change to "fq - jq for binary formats" but starting to get long :)

**Comment by wangsongyan** [comment]
this is awkward.

**Comment by wader** [comment]
No worries!
