### ISSUE TITLE
make use of kaitai struct for additional formats?

### ISSUE THREAD

**Issue by khimaros** [wader/fq#734]
just in case it isn't already on your radar: https://kaitai.io/

kaitai provides a (quite extensive) set of descriptions for common binary formats which can be compiled into bindings for a variety of languages, including Go.

it seems like fq and kaitai goals are aligned. what do you think?

**Comment by khimaros** [comment]
hmm.. looks like @wader is already thinking about this: https://twitter.com/mwader/status/1678837065536921601

**Comment by wader** [comment]
Hey, yes very much so! i've actually started working on a run time decoder for it but have stalled a bit because of other stuff. Let me know if your interested working on it, can probably cleanup and push to a WIP branch

**Comment by wader** [comment]
Can subscribe to https://github.com/wader/fq/issues/627 also if your want updates

**Comment by wader** [comment]
Let's close and continue in https://github.com/wader/fq/issues/627
