### ISSUE TITLE
Consider relicensing internal/mathex/float80.go

### ISSUE THREAD

**Issue by guilherme-puida** [wader/fq#835]
Hi! I'm working on updating fq on Debian. I noticed that internal/mathex/float89.go references the Unlicense "license". [It is not clear if code under the Unlicense can be accepted in the archives](https://lists.debian.org/debian-legal/2021/12/msg00005.html).

https://github.com/wader/fq/blob/56c47229f0efec29405a69346a40c333bfd81a04/internal/mathex/float80.go#L1-L27

I also noticed that there is only one commit that touches this file, so it should be possible to relicense it to a more conventional license. I think that just deleting the unlicense text should be enough, since the code would be licensed under the MIT license.

Thanks!

**Comment by wader** [comment]
Hi, something like this? https://github.com/wader/fq/pull/836

**Comment by guilherme-puida** [comment]
Looks perfect, thanks!

**Comment by wader** [comment]
👍 merged!
