### ISSUE TITLE
readline upgrade

### ISSUE THREAD

**Issue by slingamn** [wader/fq#940]
I just tagged a new release candidate:

https://github.com/ergochat/readline/releases/tag/v0.1.1-rc2

It has the zos patch and also adds support for the home and end keys. I'm dogfooding it in ircdog (pun not intended) but I want to get your eyes on it as well before it gets a production tag :-)

**Comment by wader** [comment]
Tried it out a bit locally and seem to work fine 👍

I noticed another unrelated thing: opt+left/right to jump word works in bash/zsh on my macbook but not with egochat/readline. has it worked before? would be nice to support

**Comment by slingamn** [comment]
Opened https://github.com/ergochat/readline/issues/59 for this

**Comment by slingamn** [comment]
Thanks, I went ahead and tagged https://github.com/ergochat/readline/releases/tag/v0.1.1 (it's the same code as rc2)

**Comment by wader** [comment]
Great, the bump config at https://github.com/wader/fq/blob/master/go.mod#L19-L22 should pick it up later today

**Comment by wader** [comment]
Closed by #942
