### ISSUE TITLE
Homebrew formula?

### ISSUE THREAD

**Issue by vergenzt** [wader/fq#983]
Hi. I've previously installed `fq` by downloading the binary. But I'd love to be able to `brew install fq-[something]` or even `brew install wader/taps/fq`. 🤷

Unfortunately it appears `brew install fq` is [taken](https://formulae.brew.sh/formula/fq)... though the [repo it's taken by](https://github.com/circonus-labs/fq) has far fewer stars at time of writing than your repo does. 🤔  (It has 284 compared to this repo's 9.7k.) I wonder whether there's some sort of process whereby a more popular homonymous project can replace a less popular incumbent. 

Any openness to making a centralized homebrew tap for now and adding to instructions? Or should I make my own tap?

**Comment by wader** [comment]
> Hi. I've previously installed `fq` by downloading the binary. But I'd love to be able to `brew install fq-[something]` or even `brew install wader/taps/fq`. 🤷

Hey! there is a tap so you can do `brew install wader/tap/fq`. Formula is here https://github.com/wader/homebrew-tap/blob/master/Formula/fq.rb and is auto updated when doing a release.

> Unfortunately it appears `brew install fq` is [taken](https://formulae.brew.sh/formula/fq)... though the [repo it's taken by](https://github.com/circonus-labs/fq) has far fewer stars at time of writing than your repo does. 🤔 (It has 284 compared to this repo's 9.7k.) I wonder whether there's some sort of process whereby a more popular homonymous project can replace a less popular incumbent.

Yeap i looked into it some years ago and noticed the name collision and lost motivation :) haven't really looked more into it as using my own tap seems to work quite well. Have no idea if homebrew has some policies about name collision or reusing an existing name. Some other name like `fq-bin` etc is probably fine also.
 
> Any openness to making a centralized homebrew tap for now and adding to instructions? Or should I make my own tap?

Yes i'm very open to get a proper official homebrew formula so please look into it if you like and i'm happy to help as much as i can.

**Comment by vergenzt** [comment]
Oh my gosh I should have RTFM 🤦‍♂️ I totally missed the `brew install wader/tap/fq` instructions in the readme. Sorry!

**Comment by wader** [comment]
No worries! 🥳 and hope fq is useful!
